package com.bitchat.core.protocol

import kotlinx.serialization.Serializable

/**
 * The core protocol data unit (PDU) for all BitChat BLE mesh communication.
 *
 * Every message exchanged between peers over Bluetooth Low Energy is encapsulated
 * in a [Packet]. The packet is serialized via `kotlinx.serialization` and transmitted
 * as a JSON payload through the BLE GATT characteristic defined in [ProtocolConstants].
 *
 * ### Wire Format
 * ```
 * ┌─────────┬──────────┬──────────┬──────────┬────────────────┬──────────┬─────┐
 * │ version │ msgType  │   ttl    │ hopCount │   timestamp    │ payload  │ sig │
 * │ (varint)│ (byte)   │ (varint) │ (varint) │ (long/int64)   │ (bytes)  │(var)│
 * └─────────┴──────────┴──────────┴──────────┴────────────────┴──────────┴─────┘
 * ```
 * Total serialized size must not exceed [ProtocolConstants.MAX_PACKET_SIZE] (512 bytes)
 * to fit within a single BLE ATT MTU transaction without fragmentation.
 *
 * ### Addressing Model
 * Packets support three addressing modes:
 * - **Unicast**: [destinationId] is set to a specific peer's ID; all other peers ignore it.
 * - **Channel broadcast**: [channelId] is set and [destinationId] is null; all peers
 *   subscribed to that channel process the packet.
 * - **Mesh broadcast**: Both [destinationId] and [channelId] are null; every peer in
 *   range processes the packet (subject to TTL and deduplication).
 *
 * ### Relay & Loop Prevention
 * Each forwarding node increments [hopCount] and decrements [ttl]. A packet is
 * dropped when `hopCount >= ttl` or when `hopCount >= MAX_HOP_COUNT`. Nodes maintain
 * a seen-message cache keyed on [messageId] to prevent processing duplicates.
 *
 * ### Security Notes
 * - [signature] contains an optional Ed25519 signature over the serialized packet
 *   content (excluding the signature field itself). It is verified when the sender
 *   has been authenticated via the handshake flow.
 * - [ttl] is capped at [ProtocolConstants.MAX_TTL] to bound the total number of
 *   relays and limit the network footprint of any single message.
 * - [timestamp] is used for message ordering and expiry checks; peers with
 *   significantly drifted clocks may experience message rejection.
 *
 * @property version  Protocol version. Currently [ProtocolConstants.PROTOCOL_VERSION] (1).
 *                    Future versions may change the wire format; receivers should
 *                    reject packets with unknown versions.
 *
 * @property messageType  Discriminator tag identifying the message role (see [PacketType]).
 *                        Determines how the remaining fields are interpreted.
 *
 * @property messageId  Globally unique identifier (UUID) for this packet. Used for
 *                      deduplication in the relay cache and as the primary equality key.
 *                      Generated by the originating node; must not be reused.
 *
 * @property senderId  Public key hash or peer identifier of the originating node.
 *                     Set once at creation and never modified by relaying nodes.
 *                     Used for identity verification and route tracing.
 *
 * @property destinationId  Target peer ID for unicast delivery, or null for
 *                          channel/mesh broadcasts. Relaying nodes forward the packet
 *                          only if this field matches their own ID or is null.
 *
 * @property channelId  Optional channel subscription identifier. When set, the packet
 *                      is delivered to all peers subscribed to this channel. Channel
 *                      messages still participate in mesh relay when TTL > 0.
 *
 * @property ttl  Time-to-live: maximum number of relay hops this packet may traverse.
 *                Each relay decrements this value. When TTL reaches 0 the packet is
 *                no longer forwarded. Initialized to [ProtocolConstants.DEFAULT_TTL];
 *                clamped to [ProtocolConstants.MAX_TTL] at send time.
 *
 * @property hopCount  Number of relay hops this packet has already traversed.
 *                     Incremented by each forwarding node. Packet is dropped when
 *                     `hopCount >= ttl` or `hopCount >= MAX_HOP_COUNT`.
 *
 * @property timestamp  Unix epoch milliseconds when the packet was created. Used for
 *                      message ordering, expiry evaluation, and session management.
 *                      Relaying nodes do NOT modify this value.
 *
 * @property payload  Application-level data carried by this packet. The interpretation
 *                    depends on [messageType] (e.g., serialized key exchange for
 *                    HANDSHAKE_INIT, encrypted ciphertext for ENCRYPTED_MESSAGE).
 *                    Maximum size is [ProtocolConstants.MAX_PAYLOAD_SIZE] (440 bytes).
 *
 * @property signature  Optional cryptographic signature (Ed25519 by default) over the
 *                      serialized packet content. Empty byte array indicates no
 *                      signature. Verification is required for authenticated message
 *                      types and optional for discovery/heartbeat.
 */
@Serializable
data class Packet(
    val version: Int = 1,
    val messageType: PacketType,
    val messageId: String,
    val senderId: String,
    val destinationId: String? = null,
    val channelId: String? = null,
    val ttl: Int = 5,
    val hopCount: Int = 0,
    val timestamp: Long = System.currentTimeMillis(),
    val payload: ByteArray = byteArrayOf(),
    val signature: ByteArray = byteArrayOf()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Packet) return false
        return messageId == other.messageId
    }

    override fun hashCode(): Int = messageId.hashCode()
}

/**
 * Enumeration of all packet types supported by the BitChat BLE mesh protocol.
 *
 * Each type is mapped to a single-byte wire identifier used in the serialized
 * packet header. The byte values are organized into logical ranges:
 *
 * | Range       | Category            |
 * |-------------|---------------------|
 * | 0x01-0x0F   | Discovery & capabilities |
 * | 0x10-0x1F   | Key exchange & authentication |
 * | 0x20-0x2F   | Data messaging |
 * | 0x30-0x3F   | Emergency / SOS |
 * | 0x40-0x4F   | Transport-level control |
 * | 0x50-0x5F   | Mesh relay |
 * | 0x60-0x6F   | Synchronization |
 * | 0x70-0x7F   | Heartbeat / liveness |
 * | 0xF0-0xFF   | Error handling |
 *
 * @property value  Single-byte wire identifier for this packet type.
 */
enum class PacketType(val value: Byte) {

    /** Peer discovery broadcast. Sent periodically to announce presence and exchange basic identity information. */
    DISCOVERY(0x01.toByte()),

    /** Capabilities advertisement. Carried in response to DISCOVERY to advertise supported features, protocols, and services. */
    CAPABILITIES(0x02.toByte()),

    /** First step of the ECDH key exchange handshake. Contains the initiator's ephemeral public key and nonce. */
    HANDSHAKE_INIT(0x10.toByte()),

    /** Responder's reply to HANDSHAKE_INIT. Contains the responder's ephemeral public key and encrypted challenge. */
    HANDSHAKE_RESPONSE(0x11.toByte()),

    /** Final confirmation of a successful handshake. Signals that the derived session key is now active. */
    HANDSHAKE_COMPLETE(0x12.toByte()),

    /** Out-of-band or secondary authentication message. Used for re-authentication or challenge-response verification. */
    AUTHENTICATE(0x13.toByte()),

    /** End-to-end encrypted unicast message. Payload is ciphertext encrypted with the established session key. */
    ENCRYPTED_MESSAGE(0x20.toByte()),

    /** Encrypted message scoped to a channel. Delivered to all peers subscribed to the target [Packet.channelId]. */
    CHANNEL_MESSAGE(0x21.toByte()),

    /** Priority emergency broadcast. Carries distress/panic content; relayed with elevated priority and extended TTL. */
    SOS_BROADCAST(0x30.toByte()),

    /** Relay of an SOS broadcast. Forwarded by peers to extend emergency message reach across the mesh. */
    SOS_RELAY(0x31.toByte()),

    /** Acknowledgment of receipt. Sent in response to messages that require delivery confirmation. */
    ACK(0x40.toByte()),

    /** Generic mesh relay envelope. Wraps an original packet for multi-hop forwarding through the mesh network. */
    RELAY(0x50.toByte()),

    /** Queue synchronization request/response. Used to exchange missed messages between peers that reconnect after a disconnect. */
    QUEUE_SYNC(0x60.toByte()),

    /** Periodic liveness beacon. Sent at [ProtocolConstants.HEARTBEAT_INTERVAL_MS] intervals to signal peer availability. */
    HEARTBEAT(0x70.toByte()),

    /** Error notification. Carries error codes and diagnostic information when a protocol-level failure occurs. */
    ERROR(0xF0.toByte());

    companion object {
        /**
         * Resolves a [PacketType] from its single-byte wire identifier.
         *
         * @param value  The raw byte value read from a serialized packet header.
         * @return The matching [PacketType], or `null` if the byte does not correspond
         *         to any known message type (forward-compatibility for future versions).
         */
        fun fromValue(value: Byte): PacketType? = entries.find { it.value == value }
    }
}
